#printing result
a=500
b=600
c=200
print("print the value of a")
print(a)
print("print the value of b")
print(b)
print("print te value of c")
print(c)
print("print the result of a+b+c")
print(a+b+c)
print("print the value of a")
print(a)
print("print the value of b")
print(b)
print("print the value of c")
print(c)
print("print the result of a-b-c")
print(a-b-c)
print("print the value of a")
print(a)
print("print the value of b")
print(b)
print("print the value of c")
print(c)
print("print the result of a*b*c")
print(a*b*c)
print("print the value of a")
print(a)
print("print the value of b")
print(b)
print("print the value of c")
print(c)
print("print the result of a/b")
print(a/b)
print("print the result of b/a")
print(b/a)
print("print the result of a/c")
print(a/c)
print("print the result of c/a")
print(c/a)
print("print the result of a%b")
print(a%b)
print("print the result of b%c")
print(b%c)
print("print the result of c%a")
print(c%a)